import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from '@/components/header/Header';
import { WalletContextApp } from '@/components/WalletContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html className="h-full bg-gray-100" lang="en">
        <body className={`${inter.className} h-full`}>
          <WalletContextApp>
            <div className="min-h-full bg-gray-900">
              <Header />
              <main className="-mt-32 bg-gray-900">
                {children}
              </main>
            </div>
          </WalletContextApp>
        </body>
      </html>
    </>
  )
}
